steps:
  - name: "node"
    entrypoint: "npm"
    args: ["install"]
  - name: "node"
    entrypoint: "npm"
    volumes:
      - name: "data"
        path: "/etl-data"
    args: ["run", "start", "--", "--out", "/etl-data"]
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: gsutil
    volumes:
      - name: "data"
        path: "/etl-data"
    args: ["-m", "cp", "-r", "/etl-data", "gs://anirona-data/"]
