timeout: 1200s
steps:
  - name: "node"
    entrypoint: "npm"
    dir: "etl"
    args: ["install"]
  - name: "node"
    entrypoint: "./node_modules/.bin/swc-node"
    env:
      - "NODE_OPTIONS=--max_old_space_size=4096"
    volumes:
      - name: "data"
        path: "/etl-data"
    dir: "etl"
    args: ["src/index.ts", "build", "--out", "/etl-data"]
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: gsutil
    volumes:
      - name: "data"
        path: "/etl-data"
    dir: "etl"
    args: ["-m", "cp", "-r", "/etl-data/*", "gs://anirona-data/"]
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: gsutil
    volumes:
      - name: "data"
        path: "/etl-data"
    dir: "etl"
    args: ["-m", "setmeta", "-h", "Content-Encoding:gzip", "gs://anirona-data/**/*.json.gz"]
